name: Build, Push, and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: wiscowApp

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build Docker image
      run: |
        docker build . -t ${{ secrets.DOCKER_USERNAME }}/wisecowapp:latest
        docker build . -t ${{ secrets.DOCKER_USERNAME }}/wisecowapp:${{ github.run_number }}

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/wisecowapp:${{ github.run_number }}
        docker push ${{ secrets.DOCKER_USERNAME }}/wisecowapp:latest
    
    - name: Run the Docker container
      run: |
        docker ps -aq | xargs -r docker stop  
        docker ps -aq | xargs -r docker rm -f 
        docker run -d -p 4499:4499 --name wisecowapp ${{ secrets.DOCKER_USERNAME }}/wisecowapp:${{ github.run_number }}
  
  deploy_to_kubernetes:
    runs-on: eks
    needs: build
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -o awscliv2.zip  
        sudo ./aws/install --update

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: latest
    - name: Configure kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.EKS_KUBECONFIG }}" > $HOME/.kube/config
    - name: Deploy to EKS
      run: |
        kubectl apply -f wisecow-deployment.yml
