name: Build, Push, and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: wiscowApp

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build Docker image
      run: |
        docker build . -t ${{ secrets.DOCKER_USERNAME }}/wisecowapp:latest
        docker build . -t ${{ secrets.DOCKER_USERNAME }}/wisecowapp:${{ github.run_number }}

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/wisecowapp:${{ github.run_number }}
        docker push ${{ secrets.DOCKER_USERNAME }}/wisecowapp:latest
    
    - name: Run the Docker container
      run: |
        docker run -d -p 4499:4499 --name wisecowapp ${{ secrets.DOCKER_USERNAME }}/wisecowapp:${{ github.run_number }}
  